In [1]:
# Dependencias
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
data = pd.read_csv("Final_Train_Dataset.csv")
data = data[['company_name_encoded','experience', 'location', 'salary']]

In [39]:
data

company_name_encoded experience  \
0                      3687    5-7 yrs   
1                       458  10-17 yrs   
2                      4195    5-9 yrs   
3                       313   7-10 yrs   
4                      1305    1-3 yrs   
...                     ...        ...   
19797                  2245  12-18 yrs   
19798                  4966    0-3 yrs   
19799                  4272   8-13 yrs   
19800                  1793    1-3 yrs   
19801                  1349    2-5 yrs   

                                                location  salary  
0                                  Delhi NCR(Vikas Puri)   6to10  
1                                                Sonepat  10to15  
2                                              Delhi NCR  15to25  
3                                              Bengaluru  10to15  
4                                                Gurgaon    3to6  
...                                                  ...     ...  
19797                                          Hyderabad  15to25  
19798  Mumbai, Bengaluru, Chennai, Hyderabad, Dehradu...    0to3  
19799                                          Hyderabad  15to25  
19800                                               Pune  10to15  
19801                                          Hyderabad  10to15  

[19802 rows x 4 columns]

In [3]:
#Limpiando datos
exp = list(data.experience)
min_ex = []
max_ex = []

for i in range(len(exp)):
   exp[i] = exp[i].replace("yrs","").strip()
   min_ex.append(int(exp[i].split("-")[0].strip()))
   max_ex.append(int(exp[i].split("-")[1].strip()))

#Agregando nuevas experiencias al nuevo dataset
data["minimum_exp"] = min_ex
data["maximum_exp"] = max_ex

In [4]:
data

company_name_encoded experience  \
0                      3687    5-7 yrs   
1                       458  10-17 yrs   
2                      4195    5-9 yrs   
3                       313   7-10 yrs   
4                      1305    1-3 yrs   
...                     ...        ...   
19797                  2245  12-18 yrs   
19798                  4966    0-3 yrs   
19799                  4272   8-13 yrs   
19800                  1793    1-3 yrs   
19801                  1349    2-5 yrs   

                                                location  salary  minimum_exp  \
0                                  Delhi NCR(Vikas Puri)   6to10            5   
1                                                Sonepat  10to15           10   
2                                              Delhi NCR  15to25            5   
3                                              Bengaluru  10to15            7   
4                                                Gurgaon    3to6            1   
...                                                  ...     ...          ...   
19797                                          Hyderabad  15to25           12   
19798  Mumbai, Bengaluru, Chennai, Hyderabad, Dehradu...    0to3            0   
19799                                          Hyderabad  15to25            8   
19800                                               Pune  10to15            1   
19801                                          Hyderabad  10to15            2   

       maximum_exp  
0                7  
1               17  
2                9  
3               10  
4                3  
...            ...  
19797           18  
19798            3  
19799           13  
19800            3  
19801            5  

[19802 rows x 6 columns]

In [5]:
#Borramos la columna de experiencia
data.drop(['experience'], inplace = True, axis = 1)
data = data[['company_name_encoded', 'location','minimum_exp', 'maximum_exp', 'salary']]
data

company_name_encoded  \
0                      3687   
1                       458   
2                      4195   
3                       313   
4                      1305   
...                     ...   
19797                  2245   
19798                  4966   
19799                  4272   
19800                  1793   
19801                  1349   

                                                location  minimum_exp  \
0                                  Delhi NCR(Vikas Puri)            5   
1                                                Sonepat           10   
2                                              Delhi NCR            5   
3                                              Bengaluru            7   
4                                                Gurgaon            1   
...                                                  ...          ...   
19797                                          Hyderabad           12   
19798  Mumbai, Bengaluru, Chennai, Hyderabad, Dehradu...            0   
19799                                          Hyderabad            8   
19800                                               Pune            1   
19801                                          Hyderabad            2   

       maximum_exp  salary  
0                7   6to10  
1               17  10to15  
2                9  15to25  
3               10  10to15  
4                3    3to6  
...            ...     ...  
19797           18  15to25  
19798            3    0to3  
19799           13  15to25  
19800            3  10to15  
19801            5  10to15  

[19802 rows x 5 columns]

In [6]:
#Label encoding location y salary
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['location'] = le.fit_transform(data['location'])
data['salary'] = le.fit_transform(data['salary'])

In [7]:
data

company_name_encoded  location  minimum_exp  maximum_exp  salary
0                      3687       597            5            7       5
1                       458      1412           10           17       1
2                      4195       525            5            9       2
3                       313       114            7           10       1
4                      1305       811            1            3       4
...                     ...       ...          ...          ...     ...
19797                  2245       863           12           18       2
19798                  4966      1117            0            3       0
19799                  4272       863            8           13       2
19800                  1793      1301            1            3       1
19801                  1349       863            2            5       1

[19802 rows x 5 columns]

In [8]:
#Reescalando datos
from sklearn.preprocessing import StandardScaler #z = (x - u) / s
sc = StandardScaler()
data[['company_name_encoded', 'location', 'minimum_exp', 'maximum_exp']] = sc.fit_transform(data[['company_name_encoded', 'location', 'minimum_exp', 'maximum_exp']])

In [9]:
data

company_name_encoded  location  minimum_exp  maximum_exp  salary
0                  0.886106 -0.211248     0.197617    -0.255930       5
1                 -1.302594  1.687695     1.689500     2.100694       1
2                  1.230441 -0.379007     0.197617     0.215395       2
3                 -1.400879 -1.336633     0.794370     0.451058       1
4                 -0.728476  0.287370    -0.995890    -1.198579       4
...                     ...       ...          ...          ...     ...
19797             -0.091319  0.408530     2.286253     2.336357       2
19798              1.753045  1.000347    -1.294266    -1.198579       0
19799              1.282634  0.408530     1.092747     1.158045       2
19800             -0.397697  1.429066    -0.995890    -1.198579       1
19801             -0.698651  0.408530    -0.697513    -0.727255       1

[19802 rows x 5 columns]

In [10]:
#Datos de entrenamiento y prueba
from sklearn.model_selection import train_test_split
training_set, validation_set = train_test_split(data, test_size = 0.2, random_state = 21)

#Dividir datos y etiquetas
X_train = training_set.iloc[:,0:-1].values
Y_train = training_set.iloc[:,-1].values
X_val = validation_set.iloc[:,0:-1].values
y_val = validation_set.iloc[:,-1].values

In [11]:
#Función para medir la exactitud a partir de una matriz de confusión
def accuracy(confusion_matrix):
   diagonal_sum = confusion_matrix.trace()
   sum_of_all_elements = confusion_matrix.sum()
   return diagonal_sum / sum_of_all_elements

In [12]:
#Importing MLPClassifier
from sklearn.neural_network import MLPClassifier

#Initializing the MLPClassifier
classifier = MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=300,activation = 'relu',solver='sgd',random_state=1)

'''
hidden_layer_sizes : Este parámetro nos permite establecer el número de capas y el número de nodos que deseamos tener en el Clasificador de Redes Neuronales. 
                    Cada elemento de la tupla representa el número de nodos en la i-ésima posición donde i es el índice de la tupla. 
                    Por lo tanto, la longitud de la tupla indica el número total de capas ocultas en la red.
max_iter: Denota el número de épocas.
activación: La función de activación para las capas ocultas.
solver: este parámetro especifica el algoritmo para la optimización del peso en los nodos.
random_state: el parámetro permite establecer una semilla para reproducir los mismos resultados'''

'\nhidden_layer_sizes : Este parámetro nos permite establecer el número de capas y el número de nodos que deseamos tener en el Clasificador de Redes Neuronales. \n                    Cada elemento de la tupla representa el número de nodos en la i-ésima posición donde i es el índice de la tupla. \n                    Por lo tanto, la longitud de la tupla indica el número total de capas ocultas en la red.\nmax_iter: Denota el número de épocas.\nactivación: La función de activación para las capas ocultas.\nsolver: este parámetro especifica el algoritmo para la optimización del peso en los nodos.\nrandom_state: el parámetro permite establecer una semilla para reproducir los mismos resultados'

In [13]:
#Entrenamos

classifier.fit(X_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(150, 100, 50), max_iter=300, random_state=1,
              solver='sgd')

In [14]:
#Predicción sobre las instancias de prueba
y_pred = classifier.predict(X_val)

In [15]:
y_pred

array([2, 2, 1, ..., 5, 2, 5])

In [16]:
y_val

array([2, 1, 2, ..., 4, 2, 2])

In [17]:
#Ahora con la matriz de confusión
from sklearn.metrics import confusion_matrix
#Comparar resultados
cm = confusion_matrix(y_pred, y_val)
cm


array([[472,  59,  32,   2, 203, 110],
       [ 56, 359, 273,  46, 118, 248],
       [ 19, 263, 389, 145,  38,  86],
       [  2,  27,  72, 107,   0,   7],
       [ 70,  34,   8,   5,  85,  84],
       [ 50, 130,  68,   8, 123, 163]], dtype=int64)

In [18]:
from sklearn.metrics import classification_report #Reporte de clasificación
display(confusion_matrix(y_pred, y_val))
clas_report=classification_report(y_pred, y_val)
print(clas_report)

array([[472,  59,  32,   2, 203, 110],
       [ 56, 359, 273,  46, 118, 248],
       [ 19, 263, 389, 145,  38,  86],
       [  2,  27,  72, 107,   0,   7],
       [ 70,  34,   8,   5,  85,  84],
       [ 50, 130,  68,   8, 123, 163]], dtype=int64)

              precision    recall  f1-score   support

           0       0.71      0.54      0.61       878
           1       0.41      0.33      0.36      1100
           2       0.46      0.41      0.44       940
           3       0.34      0.50      0.41       215
           4       0.15      0.30      0.20       286
           5       0.23      0.30      0.26       542

    accuracy                           0.40      3961
   macro avg       0.38      0.40      0.38      3961
weighted avg       0.44      0.40      0.41      3961

